# Generated by Django 5.0.4 on 2024-04-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('twitch', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
